### ISSUE TITLE
Feedback from 'Simplify GitOps with Flux and Visual Studio Code'

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/vscode-gitops-tools#228]
@gbaeke posted a nice introduction to the extension here - https://www.youtube.com/watch?v=-07emkW8eiM

As part of the demonstration, a few bugs and feature requests are highlighted:
- [x] Bug: HelmRelease objects in the Workloads view fail to finish loading - #229 
- [x] Feat: Allow a user to delete workload objects [Kustomization | HelmRelease] - #230
- [x] Feat: Update source creation form to allow for Helm Repositories - #231
- [ ] Bug: kustomization name is not fully respected when creating AKS source and kustomization - #232

**Comment by sympatheticmoose** [comment]
(apologies, for some reason GitHub was failing to convert tasks to issues so the formatting is a bit odd)

**Comment by kingdonb** [comment]
I think only #232 is still open here, I've scheduled it for another look before 0.26.0 and added it to the milestone.
